# Generated by Django 4.2.4 on 2023-08-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=256, verbose_name='Точка отправления')),
                ('destination', models.CharField(max_length=256, verbose_name='Точка прибытия')),
                ('duration', models.IntegerField(verbose_name='Длительность')),
            ],
        ),
    ]
