# Generated by Django 4.2.4 on 2023-08-31 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_passenger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ('city',), 'verbose_name': 'Аэропорт', 'verbose_name_plural': 'Аэропорты'},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ('origin', 'duration'), 'verbose_name': 'Вылет', 'verbose_name_plural': 'Вылеты'},
        ),
    ]
