# Generated by Django 4.2.4 on 2023-09-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_alter_airport_options_alter_flight_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='ЧПУ'),
        ),
    ]
