# Generated by Django 4.2.5 on 2023-09-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_airport_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=60, verbose_name='Фамилия')),
                ('rank', models.CharField(max_length=60, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник службы безопасности',
                'verbose_name_plural': 'Сотрудники службы безопасности',
            },
        ),
    ]
