# Generated by Django 4.2.5 on 2023-09-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0010_securityofficer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securityofficer',
            options={'ordering': ('name', 'second_name'), 'verbose_name': 'Сотрудник службы безопасности', 'verbose_name_plural': 'Сотрудники службы безопасности'},
        ),
    ]
